/** Empreendimentos vinculados ao site https://www.imobiliarianewpalace.com.br/ */

export const NEW_PALACE_SITE = "https://www.imobiliarianewpalace.com.br";

const CLOUDINARY = "https://res.cloudinary.com/dkgjwrjpv/image/upload";

/** Thumb otimizado: WebP/AVIF automático, qualidade eco e crop 480×320. */
function img(path: string) {
  return `${CLOUDINARY}/f_auto,q_auto:eco,w_480,h_320,c_fill,g_auto/${path}`;
}

export interface Empreendimento {
  id: string;
  slug: string;
  titulo: string;
  endereco: string;
  cidade: string;
  bairro: string;
  quartos: number;
  banheiros: number;
  area: number;
  imagem: string;
  status: "Disponível";
}

export function empreendimentoUrl(slug: string) {
  return `${NEW_PALACE_SITE}/${slug}`;
}

export const EMPREENDIMENTOS: Empreendimento[] = [
  {
    id: "np-01",
    slug: "mirante-belvedere",
    titulo: "Mirante Belvedere",
    endereco: "R. Antônio Eduardo Amorim, 141 - Imbiribeira, Recife - PE",
    cidade: "Recife",
    bairro: "Imbiribeira",
    quartos: 2,
    banheiros: 1,
    area: 36.5,
    imagem: img("v1781300066/miranteBelvedereFachada_w7pjix.jpg"),
    status: "Disponível",
  },
  {
    id: "np-02",
    slug: "araca-prime",
    titulo: "Araçá Prime",
    endereco: "Rua Engenheiro José Brandão Cavalcante, Imbiribeira, Recife - PE",
    cidade: "Recife",
    bairro: "Imbiribeira",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1781297978/aracaPrimeLocalizacao_pbon5r.jpg"),
    status: "Disponível",
  },
  {
    id: "np-03",
    slug: "bosque-recife",
    titulo: "Bosque Recife",
    endereco: "Av. da Recuperação, Passarinho, Recife - PE",
    cidade: "Recife",
    bairro: "Passarinho",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1782165298/bosqueRecifeFachada_drtvfp.jpg"),
    status: "Disponível",
  },
  {
    id: "np-04",
    slug: "alameda-dos-passaros",
    titulo: "Alameda dos Pássaros",
    endereco: "4A Travessa Pereira de Barreto, 80 - Passarinho, Recife - PE",
    cidade: "Recife",
    bairro: "Passarinho",
    quartos: 2,
    banheiros: 1,
    area: 36.73,
    imagem: img("v1782161478/alamedaDosPassarosFachada_ivflt9.jpg"),
    status: "Disponível",
  },
  {
    id: "np-05",
    slug: "jaqueira-prime-residence",
    titulo: "Jaqueira Prime Residence",
    endereco: "R. Min. Mario Andreaza - Várzea, Recife - PE",
    cidade: "Recife",
    bairro: "Várzea",
    quartos: 2,
    banheiros: 2,
    area: 43.45,
    imagem: img("v1782483218/jaqueiraPrimeResidenceFachada_eo4izl.jpg"),
    status: "Disponível",
  },
  {
    id: "np-06",
    slug: "citta-jose-ruffino-residence",
    titulo: "Città José Ruffino Residence",
    endereco: "Av. Dr. José Rufino, Barro, Recife - PE",
    cidade: "Recife",
    bairro: "Barro",
    quartos: 2,
    banheiros: 2,
    area: 46.08,
    imagem: img("v1770326708/CittaSanMartin_s9swhk.jpg"),
    status: "Disponível",
  },
  {
    id: "np-07",
    slug: "pontal-maracaipe",
    titulo: "Pontal Maracaipe",
    endereco: "Av. Nápoles, s/n, Fragoso, Paulista - PE",
    cidade: "Paulista",
    bairro: "Fragoso",
    quartos: 2,
    banheiros: 1,
    area: 42.15,
    imagem: img("v1770326728/direcionalPaulista_b6amo2.jpg"),
    status: "Disponível",
  },
  {
    id: "np-08",
    slug: "engenho-paulista",
    titulo: "Engenho Paulista",
    endereco: "Rua Canaã Nossa Sra. da Conceição, Paulista - PE",
    cidade: "Paulista",
    bairro: "Nossa Sra. da Conceição",
    quartos: 2,
    banheiros: 1,
    area: 39.34,
    imagem: img("v1770326728/direcionalPaulista_b6amo2.jpg"),
    status: "Disponível",
  },
  {
    id: "np-09",
    slug: "bandeirantes",
    titulo: "Bandeirantes",
    endereco: "R. Campo de Pouso - Maranguape I, Paulista - PE",
    cidade: "Paulista",
    bairro: "Maranguape I",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1770326728/direcionalPaulista_b6amo2.jpg"),
    status: "Disponível",
  },
  {
    id: "np-10",
    slug: "torres-marina",
    titulo: "Torres Marina",
    endereco: "R. Divinópolis - Nossa Sra. do Ó, Paulista - PE",
    cidade: "Paulista",
    bairro: "Nossa Sra. do Ó",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1770326825/empreendimentoTorresDeOlinda_vimrf6.jpg"),
    status: "Disponível",
  },
  {
    id: "np-11",
    slug: "estrada-dos-marcos-2",
    titulo: "Estrada dos Marcos II",
    endereco: "Estr. dos Marcos, Marcos, Igarassu - PE",
    cidade: "Igarassu",
    bairro: "Marcos",
    quartos: 2,
    banheiros: 1,
    area: 50,
    imagem: img("v1770326700/empreendimentoBrisasDeIgarassu_xvj9cf.webp"),
    status: "Disponível",
  },
  {
    id: "np-12",
    slug: "cita-estancia",
    titulo: "Cita Estância",
    endereco: "R. Passo da Santa Cruz, 400 - Jiquiá, Recife - PE",
    cidade: "Recife",
    bairro: "Jiquiá",
    quartos: 2,
    banheiros: 1,
    area: 34.91,
    imagem: img("v1770326708/CittaSanMartin_s9swhk.jpg"),
    status: "Disponível",
  },
  {
    id: "np-13",
    slug: "vila-das-tulipas",
    titulo: "Vila das Tulipas",
    endereco: "Av. Dr. Paulo Petribu - Pixete, São Lourenço da Mata - PE",
    cidade: "São Lourenço da Mata",
    bairro: "Pixete",
    quartos: 2,
    banheiros: 2,
    area: 49.3,
    imagem: img("v1783521611/vilaDasTulipasGuarita_zc7fy5.jpg"),
    status: "Disponível",
  },
  {
    id: "np-14",
    slug: "vila-do-reinado",
    titulo: "Vila do Reinado",
    endereco: "Av. Miguel Labanca, 801 - Centro, São Lourenço da Mata - PE",
    cidade: "São Lourenço da Mata",
    bairro: "Centro",
    quartos: 2,
    banheiros: 2,
    area: 73.58,
    imagem: img("v1770326536/vilaDasPalmeiras_rotubu.jpg"),
    status: "Disponível",
  },
  {
    id: "np-15",
    slug: "jardim-imperial",
    titulo: "Jardim Imperial",
    endereco: "Rua São José do Egito, Paulista - PE",
    cidade: "Paulista",
    bairro: "Paulista",
    quartos: 2,
    banheiros: 1,
    area: 49.32,
    imagem: img("v1770326728/direcionalPaulista_b6amo2.jpg"),
    status: "Disponível",
  },
  {
    id: "np-16",
    slug: "vale-encantado",
    titulo: "Vale Encantado",
    endereco: "Rua Eraldo Lourenço da Silva, Zona urbana de Umbura, Igarassu - PE",
    cidade: "Igarassu",
    bairro: "Umbura",
    quartos: 2,
    banheiros: 1,
    area: 49.32,
    imagem: img("v1770326700/empreendimentoBrisasDeIgarassu_xvj9cf.webp"),
    status: "Disponível",
  },
  {
    id: "np-17",
    slug: "patio-hori",
    titulo: "Patio Hori",
    endereco: "Caxangá, Recife - PE",
    cidade: "Recife",
    bairro: "Caxangá",
    quartos: 2,
    banheiros: 2,
    area: 52.28,
    imagem: img("v1770837207/patioHoriFachada_fexmxb.jpg"),
    status: "Disponível",
  },
  {
    id: "np-18",
    slug: "start-recife",
    titulo: "Condomínio Start Recife",
    endereco: "Estrada da Mumbeca, Guabiraba, Recife - PE",
    cidade: "Recife",
    bairro: "Guabiraba",
    quartos: 2,
    banheiros: 1,
    area: 42,
    imagem: img("v1770326815/empreendimentoStartRecife_qfyekj.jpg"),
    status: "Disponível",
  },
  {
    id: "np-19",
    slug: "start-costa-dourada",
    titulo: "Condomínio Start Costa Dourada",
    endereco: "Av. Almirante Paulo Moreira, Garapu, Cabo de Santo Agostinho - PE",
    cidade: "Cabo de Santo Agostinho",
    bairro: "Garapu",
    quartos: 2,
    banheiros: 1,
    area: 47.38,
    imagem: img("v1770326804/StartCostaDouradaPiscina_ztzujb.jpg"),
    status: "Disponível",
  },
  {
    id: "np-20",
    slug: "start-costa-dourada2",
    titulo: "Condomínio Start Costa Dourada II",
    endereco: "Ibimirim, s/n, Garapu, Cabo De Santo Agostinho - PE",
    cidade: "Cabo de Santo Agostinho",
    bairro: "Garapu",
    quartos: 2,
    banheiros: 1,
    area: 44.75,
    imagem: img("v1770326809/startCostaDourada2Portaria_d2iyva.png"),
    status: "Disponível",
  },
  {
    id: "np-21",
    slug: "direcional-paulista",
    titulo: "Direcional Paulista",
    endereco: "Maranguape I, Paulista - PE",
    cidade: "Paulista",
    bairro: "Maranguape I",
    quartos: 2,
    banheiros: 1,
    area: 48.62,
    imagem: img("v1770326728/direcionalPaulista_b6amo2.jpg"),
    status: "Disponível",
  },
  {
    id: "np-22",
    slug: "aurora-dos-passaros",
    titulo: "Aurora dos Passaros",
    endereco: "Via Local D - Aurora, Paulista - PE",
    cidade: "Paulista",
    bairro: "Aurora",
    quartos: 2,
    banheiros: 2,
    area: 45.46,
    imagem: img("v1770326635/empreendimentoAuroraDosPassaros_vdadki.jpg"),
    status: "Disponível",
  },
  {
    id: "np-23",
    slug: "bosque-das-acacias",
    titulo: "Bosque das Acácias",
    endereco: "Rua das Oliveiras, 155 - Dois Carneiros, Jaboatão dos Guararapes - PE",
    cidade: "Jaboatão dos Guararapes",
    bairro: "Dois Carneiros",
    quartos: 2,
    banheiros: 1,
    area: 40.81,
    imagem: img("v1770326653/empreendimentoBosqueDasAcacias_p5zg4x.jpg"),
    status: "Disponível",
  },
  {
    id: "np-24",
    slug: "botanik-torre",
    titulo: "Botanik Torre",
    endereco: "R. Real da Torre, 1130 - Torre, Recife - PE",
    cidade: "Recife",
    bairro: "Torre",
    quartos: 3,
    banheiros: 3,
    area: 76.45,
    imagem: img("v1770326674/empreendimentoBotanikTorre_fwmjkx.jpg"),
    status: "Disponível",
  },
  {
    id: "np-25",
    slug: "brisas-dos-nobres",
    titulo: "Brisa dos Nobres",
    endereco: "R. Des. Virgílio de Sá Pereira, 567 - Cordeiro, Recife - PE",
    cidade: "Recife",
    bairro: "Cordeiro",
    quartos: 3,
    banheiros: 3,
    area: 71.2,
    imagem: img("v1770326692/empreendimentoBrisaDosNobres_kcaqav.jpg"),
    status: "Disponível",
  },
  {
    id: "np-26",
    slug: "brisas-de-igarassu",
    titulo: "Brisas de Igarassu",
    endereco: "Alameda dos Otis, S/N, Santa Luzia, Igarassu - PE",
    cidade: "Igarassu",
    bairro: "Santa Luzia",
    quartos: 2,
    banheiros: 1,
    area: 47.25,
    imagem: img("v1770326700/empreendimentoBrisasDeIgarassu_xvj9cf.webp"),
    status: "Disponível",
  },
  {
    id: "np-27",
    slug: "candeias-garden",
    titulo: "Candeias Garden",
    endereco: "R. Cel. Kléber de Andrade, 1720 - Candeias, Jaboatão dos Guararapes - PE",
    cidade: "Jaboatão dos Guararapes",
    bairro: "Candeias",
    quartos: 2,
    banheiros: 1,
    area: 40.28,
    imagem: img("v1770326705/candeiasGardenPiscina_vnqoqq.jpg"),
    status: "Disponível",
  },
  {
    id: "np-28",
    slug: "citta-san-martin",
    titulo: "Citta San Martin",
    endereco: "R. Comendador Queirós de Oliveira, 220 - San Martin, Recife - PE",
    cidade: "Recife",
    bairro: "San Martin",
    quartos: 2,
    banheiros: 1,
    area: 34.73,
    imagem: img("v1770326708/CittaSanMartin_s9swhk.jpg"),
    status: "Disponível",
  },
  {
    id: "np-29",
    slug: "condominio-rio-capibaribe",
    titulo: "Condomínio Rio Capibaribe",
    endereco: "R. Expedicionário Constantino Avelino de Sá, Capibaribe, São Lourenço da Mata - PE",
    cidade: "São Lourenço da Mata",
    bairro: "Capibaribe",
    quartos: 2,
    banheiros: 1,
    area: 56.38,
    imagem: img("v1770326717/CondominioRioCapibaribe_vkvbnp.jpg"),
    status: "Disponível",
  },
  {
    id: "np-30",
    slug: "conquista-jaboatao",
    titulo: "Conquista Jaboatão",
    endereco: "Via Principal, 459, Sucupira - Jaboatão dos Guararapes",
    cidade: "Jaboatão dos Guararapes",
    bairro: "Sucupira",
    quartos: 2,
    banheiros: 1,
    area: 36.24,
    imagem: img("v1770326726/empreendimentoConquistaJaboatao_i9r3fs.jpg"),
    status: "Disponível",
  },
  {
    id: "np-31",
    slug: "like-boa-vista",
    titulo: "Like Boa Vista",
    endereco: "R. do Príncipe, 120, Boa Vista, Recife - PE",
    cidade: "Recife",
    bairro: "Boa Vista",
    quartos: 2,
    banheiros: 1,
    area: 42.66,
    imagem: img("v1770326731/empreendimentoLikeBoaVista_bmd9f0.png"),
    status: "Disponível",
  },
  {
    id: "np-32",
    slug: "mada-studios",
    titulo: "Mada Studios",
    endereco: "R. Real da Torre, 479, Madalena - Recife - PE",
    cidade: "Recife",
    bairro: "Madalena",
    quartos: 1,
    banheiros: 1,
    area: 26,
    imagem: img("v1770326736/empreendimentoMada_bmlh8h.webp"),
    status: "Disponível",
  },
  {
    id: "np-33",
    slug: "morada-beberibe",
    titulo: "Morada Beberibe",
    endereco: "Av. Arlindo dos Oito Baixos, s/n - Dois Unidos - Zona Norte - Recife - PE",
    cidade: "Recife",
    bairro: "Dois Unidos",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1770326740/moradaBeberibe_lsyiln.jpg"),
    status: "Disponível",
  },
  {
    id: "np-34",
    slug: "morada-capibaribe2",
    titulo: "Morada Capibaribe II",
    endereco: "Dois Unidos, Recife - PE",
    cidade: "Recife",
    bairro: "Dois Unidos",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1770326744/moradaCapibaribe2_l8wwau.jpg"),
    status: "Disponível",
  },
  {
    id: "np-35",
    slug: "nascente-do-capibaribe",
    titulo: "Nascente do Capibaribe",
    endereco: "R. Vinte e Nove-A, 3 - A1/3 - Parque Capibaribe, São Lourenço da Mata - PE",
    cidade: "São Lourenço da Mata",
    bairro: "Parque Capibaribe",
    quartos: 2,
    banheiros: 1,
    area: 57.81,
    imagem: img("v1770326757/nascenteDoCapibaribe_wrisce.jpg"),
    status: "Disponível",
  },
  {
    id: "np-36",
    slug: "paco-deco",
    titulo: "Paço Decó",
    endereco: "R. Real da Torre, 479 - Madalena, Recife - PE",
    cidade: "Recife",
    bairro: "Madalena",
    quartos: 3,
    banheiros: 4,
    area: 108,
    imagem: img("v1770326768/empreendimentoPacoDeco_vcchu7.jpg"),
    status: "Disponível",
  },
  {
    id: "np-37",
    slug: "patio-nattu",
    titulo: "Patio Nattú",
    endereco: "R. Adelmar Lafaiete, 16 - Caxangá, Recife - PE",
    cidade: "Recife",
    bairro: "Caxangá",
    quartos: 2,
    banheiros: 2,
    area: 45.26,
    imagem: img("v1770326777/empreendimentoPatioNattiu_of87jn.jpg"),
    status: "Disponível",
  },
  {
    id: "np-38",
    slug: "patio-solare",
    titulo: "Patio Solare",
    endereco: "R. Professsor Pedro Augusto Carneiro Leão, 13 - Imbiribeira, Recife - PE",
    cidade: "Recife",
    bairro: "Imbiribeira",
    quartos: 2,
    banheiros: 2,
    area: 49.11,
    imagem: img("v1770326783/empreendimentoPatioSolare_r3p0ow.jpg"),
    status: "Disponível",
  },
  {
    id: "np-39",
    slug: "premier-residence",
    titulo: "Premier Residence",
    endereco: "Rua Lago Verde, 151, Iputinga - Recife - PE",
    cidade: "Recife",
    bairro: "Iputinga",
    quartos: 2,
    banheiros: 1,
    area: 37.95,
    imagem: img("v1770326789/PremierResidence_tuwzyt.jpg"),
    status: "Disponível",
  },
  {
    id: "np-40",
    slug: "residencial-real-prime",
    titulo: "Residencial Real Prime",
    endereco: "Rua Maranguape, 516. Santa Mônica, Camaragibe - PE",
    cidade: "Camaragibe",
    bairro: "Santa Mônica",
    quartos: 2,
    banheiros: 1,
    area: 40.28,
    imagem: img("v1770326793/empreendimentoRealPrime_hheams.jpg"),
    status: "Disponível",
  },
  {
    id: "np-41",
    slug: "rooftop-olinda-prime",
    titulo: "Rooftop Olinda Prime",
    endereco: "R. Rodizita, 390a - Jardim Atlântico, Olinda - PE",
    cidade: "Olinda",
    bairro: "Jardim Atlântico",
    quartos: 2,
    banheiros: 1,
    area: 39.78,
    imagem: img("v1770326797/empreendimentoRooftopOlindaPrime_okl7cm.jpg"),
    status: "Disponível",
  },
  {
    id: "np-42",
    slug: "tivo-studio",
    titulo: "Tivo Studio",
    endereco: "R. Teles Júnior, 16 - Aflitos, Recife - PE",
    cidade: "Recife",
    bairro: "Aflitos",
    quartos: 1,
    banheiros: 1,
    area: 20.74,
    imagem: img("v1770326821/empreendimentoTivo_f527q9.jpg"),
    status: "Disponível",
  },
  {
    id: "np-43",
    slug: "torres-de-olinda",
    titulo: "Torres de Olinda",
    endereco: "Av. Transamazônica - Jardim Brasil, Olinda - PE",
    cidade: "Olinda",
    bairro: "Jardim Brasil",
    quartos: 2,
    banheiros: 2,
    area: 45.46,
    imagem: img("v1770326825/empreendimentoTorresDeOlinda_vimrf6.jpg"),
    status: "Disponível",
  },
  {
    id: "np-44",
    slug: "vale-caxanga",
    titulo: "Vale Caxanga Golf Club",
    endereco: "R. Caxangá Ágape, 4643 - Várzea, Recife - PE",
    cidade: "Recife",
    bairro: "Várzea",
    quartos: 2,
    banheiros: 2,
    area: 61.53,
    imagem: img("v1770326520/valeCaxanga_muiwc0.jpg"),
    status: "Disponível",
  },
  {
    id: "np-45",
    slug: "varzea-prime",
    titulo: "Varzea Prime",
    endereco: "R. Min. Mario Andreaza, Várzea, Recife - PE",
    cidade: "Recife",
    bairro: "Várzea",
    quartos: 2,
    banheiros: 1,
    area: 46.45,
    imagem: img("v1770326529/empreendimentoVarzeaPrime_v13ypy.jpg"),
    status: "Disponível",
  },
  {
    id: "np-46",
    slug: "vila-das-palmeiras",
    titulo: "Vila das Palmeiras",
    endereco: "Maranguape II, Paulista - PE",
    cidade: "Paulista",
    bairro: "Maranguape II",
    quartos: 3,
    banheiros: 2,
    area: 60.05,
    imagem: img("v1770326536/vilaDasPalmeiras_rotubu.jpg"),
    status: "Disponível",
  },
  {
    id: "np-47",
    slug: "vista-do-golf",
    titulo: "Vista do Golf",
    endereco: "R. Emíliano Braga, 1069 - Várzea - Zona Norte, Recife - PE",
    cidade: "Recife",
    bairro: "Várzea",
    quartos: 2,
    banheiros: 1,
    area: 36.7,
    imagem: img("v1770326542/vistaDoGolf_tficg4.jpg"),
    status: "Disponível",
  },
  {
    id: "np-48",
    slug: "viva-casa-amarela",
    titulo: "Viva Casa Amarela",
    endereco: "Rua Luiz Cesário de Melo, 55 - Vasco da Gama, Recife - PE",
    cidade: "Recife",
    bairro: "Vasco da Gama",
    quartos: 2,
    banheiros: 1,
    area: 36.5,
    imagem: img("v1770326546/vivaCasaAmarela_fotora.jpg"),
    status: "Disponível",
  },
  {
    id: "np-49",
    slug: "viva-vida-jardim-botanico",
    titulo: "Viva Vida Jardim Botânico",
    endereco: "Av. Santa luzia, 536 – Curado III, Jaboatão dos Guararapes - PE",
    cidade: "Jaboatão dos Guararapes",
    bairro: "Curado III",
    quartos: 2,
    banheiros: 1,
    area: 36.24,
    imagem: img("v1770326554/empreendimentoVivaVidaJardimBotanico_iecfpy.jpg"),
    status: "Disponível",
  },
  {
    id: "np-50",
    slug: "viva-vida-primavera",
    titulo: "Viva Vida Primavera",
    endereco: "Nova Tiúma, São Lourenço da Mata - PE",
    cidade: "São Lourenço da Mata",
    bairro: "Nova Tiúma",
    quartos: 2,
    banheiros: 1,
    area: 36,
    imagem: img("v1770326598/vivaVivaPimavera_leoqch.jpg"),
    status: "Disponível",
  },
  {
    id: "np-51",
    slug: "viva-vida-sao-lorenco",
    titulo: "Viva Vida São Lourenço",
    endereco: "Nova Tiúma, São Lourenço da Mata - PE",
    cidade: "São Lourenço da Mata",
    bairro: "Nova Tiúma",
    quartos: 2,
    banheiros: 1,
    area: 36.24,
    imagem: img("v1770326603/empreendimentoVivaVidaSaoLorenco_la7nsj.jpg"),
    status: "Disponível",
  },
];

export const EMPREENDIMENTO_CIDADES = [
  ...new Set(EMPREENDIMENTOS.map((e) => e.cidade)),
].sort((a, b) => a.localeCompare(b, "pt-BR"));
