/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppClientesPerdidosRouteImport } from './routes/_app.clientes-perdidos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppConstrutorasRouteImport } from './routes/_app.construtoras'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppCorretoresRouteImport } from './routes/_app.corretores'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentacaoRouteImport } from './routes/_app.documentacao'
import { Route as AppEquipesRouteImport } from './routes/_app.equipes'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppFunilRouteImport } from './routes/_app.funil'
import { Route as AppFunilClientesRouteImport } from './routes/_app.funil-clientes'
import { Route as AppGuiaRouteImport } from './routes/_app.guia'
import { Route as AppImoveisRouteImport } from './routes/_app.imoveis'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLeadsPerdidosRouteImport } from './routes/_app.leads-perdidos'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPropostasRouteImport } from './routes/_app.propostas'
import { Route as AppResultadoRouteImport } from './routes/_app.resultado'
import { Route as AppTaxaConversaoRouteImport } from './routes/_app.taxa-conversao'
import { Route as AppTenantsRouteImport } from './routes/_app.tenants'
import { Route as AppTriagemRouteImport } from './routes/_app.triagem'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppVendasRouteImport } from './routes/_app.vendas'
import { Route as ProdutosCrmImobiliarioRouteImport } from './routes/produtos.crm-imobiliario'
import { Route as ProdutosIaWhatsappRouteImport } from './routes/produtos.ia-whatsapp'
import { Route as ProdutosSitesInstitucionaisRouteImport } from './routes/produtos.sites-institucionais'
import { Route as AppFinanceiroCategoriasRouteImport } from './routes/_app.financeiro.categorias'
import { Route as AppFinanceiroCentroDespesasRouteImport } from './routes/_app.financeiro.centro-despesas'
import { Route as AppFinanceiroCentroRecebimentosRouteImport } from './routes/_app.financeiro.centro-recebimentos'
import { Route as AppFinanceiroClientesFornecedoresRouteImport } from './routes/_app.financeiro.clientes-fornecedores'
import { Route as AppFinanceiroComissaoRouteImport } from './routes/_app.financeiro.comissao'
import { Route as AppFinanceiroContasAPagarRouteImport } from './routes/_app.financeiro.contas-a-pagar'
import { Route as AppFinanceiroContasAReceberRouteImport } from './routes/_app.financeiro.contas-a-receber'
import { Route as AppFinanceiroContratosRouteImport } from './routes/_app.financeiro.contratos'
import { Route as AppFinanceiroFluxoCaixaRouteImport } from './routes/_app.financeiro.fluxo-caixa'
import { Route as AppFinanceiroMovimentacaoRouteImport } from './routes/_app.financeiro.movimentacao'
import { Route as AppFinanceiroVisaoGeralRouteImport } from './routes/_app.financeiro.visao-geral'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesPerdidosRoute = AppClientesPerdidosRouteImport.update({
  id: '/clientes-perdidos',
  path: '/clientes-perdidos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConstrutorasRoute = AppConstrutorasRouteImport.update({
  id: '/construtoras',
  path: '/construtoras',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentacaoRoute = AppDocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipesRoute = AppEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFunilRoute = AppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppRoute,
} as any)
const AppFunilClientesRoute = AppFunilClientesRouteImport.update({
  id: '/funil-clientes',
  path: '/funil-clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiaRoute = AppGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisRoute = AppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsPerdidosRoute = AppLeadsPerdidosRouteImport.update({
  id: '/leads-perdidos',
  path: '/leads-perdidos',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppResultadoRoute = AppResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxaConversaoRoute = AppTaxaConversaoRouteImport.update({
  id: '/taxa-conversao',
  path: '/taxa-conversao',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTriagemRoute = AppTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const ProdutosCrmImobiliarioRoute = ProdutosCrmImobiliarioRouteImport.update({
  id: '/produtos/crm-imobiliario',
  path: '/produtos/crm-imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIaWhatsappRoute = ProdutosIaWhatsappRouteImport.update({
  id: '/produtos/ia-whatsapp',
  path: '/produtos/ia-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSitesInstitucionaisRoute =
  ProdutosSitesInstitucionaisRouteImport.update({
    id: '/produtos/sites-institucionais',
    path: '/produtos/sites-institucionais',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppFinanceiroCategoriasRoute = AppFinanceiroCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCentroDespesasRoute =
  AppFinanceiroCentroDespesasRouteImport.update({
    id: '/centro-despesas',
    path: '/centro-despesas',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroCentroRecebimentosRoute =
  AppFinanceiroCentroRecebimentosRouteImport.update({
    id: '/centro-recebimentos',
    path: '/centro-recebimentos',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroClientesFornecedoresRoute =
  AppFinanceiroClientesFornecedoresRouteImport.update({
    id: '/clientes-fornecedores',
    path: '/clientes-fornecedores',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroComissaoRoute = AppFinanceiroComissaoRouteImport.update({
  id: '/comissao',
  path: '/comissao',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroContasAPagarRoute =
  AppFinanceiroContasAPagarRouteImport.update({
    id: '/contas-a-pagar',
    path: '/contas-a-pagar',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContasAReceberRoute =
  AppFinanceiroContasAReceberRouteImport.update({
    id: '/contas-a-receber',
    path: '/contas-a-receber',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContratosRoute = AppFinanceiroContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroFluxoCaixaRoute = AppFinanceiroFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroMovimentacaoRoute =
  AppFinanceiroMovimentacaoRouteImport.update({
    id: '/movimentacao',
    path: '/movimentacao',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroVisaoGeralRoute = AppFinanceiroVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppFinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/clientes-perdidos': typeof AppClientesPerdidosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/construtoras': typeof AppConstrutorasRoute
  '/contratos': typeof AppContratosRoute
  '/corretores': typeof AppCorretoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentacao': typeof AppDocumentacaoRoute
  '/equipes': typeof AppEquipesRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/funil': typeof AppFunilRoute
  '/funil-clientes': typeof AppFunilClientesRoute
  '/guia': typeof AppGuiaRoute
  '/imoveis': typeof AppImoveisRoute
  '/leads': typeof AppLeadsRoute
  '/leads-perdidos': typeof AppLeadsPerdidosRoute
  '/metas': typeof AppMetasRoute
  '/perfil': typeof AppPerfilRoute
  '/propostas': typeof AppPropostasRoute
  '/resultado': typeof AppResultadoRoute
  '/taxa-conversao': typeof AppTaxaConversaoRoute
  '/tenants': typeof AppTenantsRoute
  '/triagem': typeof AppTriagemRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas': typeof AppVendasRoute
  '/produtos/crm-imobiliario': typeof ProdutosCrmImobiliarioRoute
  '/produtos/ia-whatsapp': typeof ProdutosIaWhatsappRoute
  '/produtos/sites-institucionais': typeof ProdutosSitesInstitucionaisRoute
  '/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/financeiro/centro-recebimentos': typeof AppFinanceiroCentroRecebimentosRoute
  '/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/financeiro/comissao': typeof AppFinanceiroComissaoRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/contratos': typeof AppFinanceiroContratosRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/clientes-perdidos': typeof AppClientesPerdidosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/construtoras': typeof AppConstrutorasRoute
  '/contratos': typeof AppContratosRoute
  '/corretores': typeof AppCorretoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentacao': typeof AppDocumentacaoRoute
  '/equipes': typeof AppEquipesRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/funil': typeof AppFunilRoute
  '/funil-clientes': typeof AppFunilClientesRoute
  '/guia': typeof AppGuiaRoute
  '/imoveis': typeof AppImoveisRoute
  '/leads': typeof AppLeadsRoute
  '/leads-perdidos': typeof AppLeadsPerdidosRoute
  '/metas': typeof AppMetasRoute
  '/perfil': typeof AppPerfilRoute
  '/propostas': typeof AppPropostasRoute
  '/resultado': typeof AppResultadoRoute
  '/taxa-conversao': typeof AppTaxaConversaoRoute
  '/tenants': typeof AppTenantsRoute
  '/triagem': typeof AppTriagemRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas': typeof AppVendasRoute
  '/produtos/crm-imobiliario': typeof ProdutosCrmImobiliarioRoute
  '/produtos/ia-whatsapp': typeof ProdutosIaWhatsappRoute
  '/produtos/sites-institucionais': typeof ProdutosSitesInstitucionaisRoute
  '/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/financeiro/centro-recebimentos': typeof AppFinanceiroCentroRecebimentosRoute
  '/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/financeiro/comissao': typeof AppFinanceiroComissaoRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/contratos': typeof AppFinanceiroContratosRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demonstracao': typeof DemonstracaoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/clientes-perdidos': typeof AppClientesPerdidosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/construtoras': typeof AppConstrutorasRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/corretores': typeof AppCorretoresRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documentacao': typeof AppDocumentacaoRoute
  '/_app/equipes': typeof AppEquipesRoute
  '/_app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/_app/funil': typeof AppFunilRoute
  '/_app/funil-clientes': typeof AppFunilClientesRoute
  '/_app/guia': typeof AppGuiaRoute
  '/_app/imoveis': typeof AppImoveisRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/leads-perdidos': typeof AppLeadsPerdidosRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/propostas': typeof AppPropostasRoute
  '/_app/resultado': typeof AppResultadoRoute
  '/_app/taxa-conversao': typeof AppTaxaConversaoRoute
  '/_app/tenants': typeof AppTenantsRoute
  '/_app/triagem': typeof AppTriagemRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/vendas': typeof AppVendasRoute
  '/produtos/crm-imobiliario': typeof ProdutosCrmImobiliarioRoute
  '/produtos/ia-whatsapp': typeof ProdutosIaWhatsappRoute
  '/produtos/sites-institucionais': typeof ProdutosSitesInstitucionaisRoute
  '/_app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/_app/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/_app/financeiro/centro-recebimentos': typeof AppFinanceiroCentroRecebimentosRoute
  '/_app/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/_app/financeiro/comissao': typeof AppFinanceiroComissaoRoute
  '/_app/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/_app/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/_app/financeiro/contratos': typeof AppFinanceiroContratosRoute
  '/_app/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/_app/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/_app/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demonstracao'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/agenda'
    | '/clientes'
    | '/clientes-perdidos'
    | '/configuracoes'
    | '/construtoras'
    | '/contratos'
    | '/corretores'
    | '/dashboard'
    | '/documentacao'
    | '/equipes'
    | '/financeiro'
    | '/funil'
    | '/funil-clientes'
    | '/guia'
    | '/imoveis'
    | '/leads'
    | '/leads-perdidos'
    | '/metas'
    | '/perfil'
    | '/propostas'
    | '/resultado'
    | '/taxa-conversao'
    | '/tenants'
    | '/triagem'
    | '/usuarios'
    | '/vendas'
    | '/produtos/crm-imobiliario'
    | '/produtos/ia-whatsapp'
    | '/produtos/sites-institucionais'
    | '/financeiro/categorias'
    | '/financeiro/centro-despesas'
    | '/financeiro/centro-recebimentos'
    | '/financeiro/clientes-fornecedores'
    | '/financeiro/comissao'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/contratos'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/movimentacao'
    | '/financeiro/visao-geral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demonstracao'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/agenda'
    | '/clientes'
    | '/clientes-perdidos'
    | '/configuracoes'
    | '/construtoras'
    | '/contratos'
    | '/corretores'
    | '/dashboard'
    | '/documentacao'
    | '/equipes'
    | '/financeiro'
    | '/funil'
    | '/funil-clientes'
    | '/guia'
    | '/imoveis'
    | '/leads'
    | '/leads-perdidos'
    | '/metas'
    | '/perfil'
    | '/propostas'
    | '/resultado'
    | '/taxa-conversao'
    | '/tenants'
    | '/triagem'
    | '/usuarios'
    | '/vendas'
    | '/produtos/crm-imobiliario'
    | '/produtos/ia-whatsapp'
    | '/produtos/sites-institucionais'
    | '/financeiro/categorias'
    | '/financeiro/centro-despesas'
    | '/financeiro/centro-recebimentos'
    | '/financeiro/clientes-fornecedores'
    | '/financeiro/comissao'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/contratos'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/movimentacao'
    | '/financeiro/visao-geral'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demonstracao'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/_app/agenda'
    | '/_app/clientes'
    | '/_app/clientes-perdidos'
    | '/_app/configuracoes'
    | '/_app/construtoras'
    | '/_app/contratos'
    | '/_app/corretores'
    | '/_app/dashboard'
    | '/_app/documentacao'
    | '/_app/equipes'
    | '/_app/financeiro'
    | '/_app/funil'
    | '/_app/funil-clientes'
    | '/_app/guia'
    | '/_app/imoveis'
    | '/_app/leads'
    | '/_app/leads-perdidos'
    | '/_app/metas'
    | '/_app/perfil'
    | '/_app/propostas'
    | '/_app/resultado'
    | '/_app/taxa-conversao'
    | '/_app/tenants'
    | '/_app/triagem'
    | '/_app/usuarios'
    | '/_app/vendas'
    | '/produtos/crm-imobiliario'
    | '/produtos/ia-whatsapp'
    | '/produtos/sites-institucionais'
    | '/_app/financeiro/categorias'
    | '/_app/financeiro/centro-despesas'
    | '/_app/financeiro/centro-recebimentos'
    | '/_app/financeiro/clientes-fornecedores'
    | '/_app/financeiro/comissao'
    | '/_app/financeiro/contas-a-pagar'
    | '/_app/financeiro/contas-a-receber'
    | '/_app/financeiro/contratos'
    | '/_app/financeiro/fluxo-caixa'
    | '/_app/financeiro/movimentacao'
    | '/_app/financeiro/visao-geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemonstracaoRoute: typeof DemonstracaoRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ProdutosCrmImobiliarioRoute: typeof ProdutosCrmImobiliarioRoute
  ProdutosIaWhatsappRoute: typeof ProdutosIaWhatsappRoute
  ProdutosSitesInstitucionaisRoute: typeof ProdutosSitesInstitucionaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes-perdidos': {
      id: '/_app/clientes-perdidos'
      path: '/clientes-perdidos'
      fullPath: '/clientes-perdidos'
      preLoaderRoute: typeof AppClientesPerdidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/construtoras': {
      id: '/_app/construtoras'
      path: '/construtoras'
      fullPath: '/construtoras'
      preLoaderRoute: typeof AppConstrutorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corretores': {
      id: '/_app/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentacao': {
      id: '/_app/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof AppDocumentacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipes': {
      id: '/_app/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AppEquipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funil': {
      id: '/_app/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AppFunilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funil-clientes': {
      id: '/_app/funil-clientes'
      path: '/funil-clientes'
      fullPath: '/funil-clientes'
      preLoaderRoute: typeof AppFunilClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guia': {
      id: '/_app/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof AppGuiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imoveis': {
      id: '/_app/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AppImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-perdidos': {
      id: '/_app/leads-perdidos'
      path: '/leads-perdidos'
      fullPath: '/leads-perdidos'
      preLoaderRoute: typeof AppLeadsPerdidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propostas': {
      id: '/_app/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resultado': {
      id: '/_app/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof AppResultadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/taxa-conversao': {
      id: '/_app/taxa-conversao'
      path: '/taxa-conversao'
      fullPath: '/taxa-conversao'
      preLoaderRoute: typeof AppTaxaConversaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triagem': {
      id: '/_app/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AppTriagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/produtos/crm-imobiliario': {
      id: '/produtos/crm-imobiliario'
      path: '/produtos/crm-imobiliario'
      fullPath: '/produtos/crm-imobiliario'
      preLoaderRoute: typeof ProdutosCrmImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/ia-whatsapp': {
      id: '/produtos/ia-whatsapp'
      path: '/produtos/ia-whatsapp'
      fullPath: '/produtos/ia-whatsapp'
      preLoaderRoute: typeof ProdutosIaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/sites-institucionais': {
      id: '/produtos/sites-institucionais'
      path: '/produtos/sites-institucionais'
      fullPath: '/produtos/sites-institucionais'
      preLoaderRoute: typeof ProdutosSitesInstitucionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/financeiro/categorias': {
      id: '/_app/financeiro/categorias'
      path: '/categorias'
      fullPath: '/financeiro/categorias'
      preLoaderRoute: typeof AppFinanceiroCategoriasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/centro-despesas': {
      id: '/_app/financeiro/centro-despesas'
      path: '/centro-despesas'
      fullPath: '/financeiro/centro-despesas'
      preLoaderRoute: typeof AppFinanceiroCentroDespesasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/centro-recebimentos': {
      id: '/_app/financeiro/centro-recebimentos'
      path: '/centro-recebimentos'
      fullPath: '/financeiro/centro-recebimentos'
      preLoaderRoute: typeof AppFinanceiroCentroRecebimentosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/clientes-fornecedores': {
      id: '/_app/financeiro/clientes-fornecedores'
      path: '/clientes-fornecedores'
      fullPath: '/financeiro/clientes-fornecedores'
      preLoaderRoute: typeof AppFinanceiroClientesFornecedoresRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/comissao': {
      id: '/_app/financeiro/comissao'
      path: '/comissao'
      fullPath: '/financeiro/comissao'
      preLoaderRoute: typeof AppFinanceiroComissaoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-a-pagar': {
      id: '/_app/financeiro/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof AppFinanceiroContasAPagarRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-a-receber': {
      id: '/_app/financeiro/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof AppFinanceiroContasAReceberRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contratos': {
      id: '/_app/financeiro/contratos'
      path: '/contratos'
      fullPath: '/financeiro/contratos'
      preLoaderRoute: typeof AppFinanceiroContratosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/fluxo-caixa': {
      id: '/_app/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AppFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/movimentacao': {
      id: '/_app/financeiro/movimentacao'
      path: '/movimentacao'
      fullPath: '/financeiro/movimentacao'
      preLoaderRoute: typeof AppFinanceiroMovimentacaoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/visao-geral': {
      id: '/_app/financeiro/visao-geral'
      path: '/visao-geral'
      fullPath: '/financeiro/visao-geral'
      preLoaderRoute: typeof AppFinanceiroVisaoGeralRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
  }
}

interface AppFinanceiroRouteChildren {
  AppFinanceiroCategoriasRoute: typeof AppFinanceiroCategoriasRoute
  AppFinanceiroCentroDespesasRoute: typeof AppFinanceiroCentroDespesasRoute
  AppFinanceiroCentroRecebimentosRoute: typeof AppFinanceiroCentroRecebimentosRoute
  AppFinanceiroClientesFornecedoresRoute: typeof AppFinanceiroClientesFornecedoresRoute
  AppFinanceiroComissaoRoute: typeof AppFinanceiroComissaoRoute
  AppFinanceiroContasAPagarRoute: typeof AppFinanceiroContasAPagarRoute
  AppFinanceiroContasAReceberRoute: typeof AppFinanceiroContasAReceberRoute
  AppFinanceiroContratosRoute: typeof AppFinanceiroContratosRoute
  AppFinanceiroFluxoCaixaRoute: typeof AppFinanceiroFluxoCaixaRoute
  AppFinanceiroMovimentacaoRoute: typeof AppFinanceiroMovimentacaoRoute
  AppFinanceiroVisaoGeralRoute: typeof AppFinanceiroVisaoGeralRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCategoriasRoute: AppFinanceiroCategoriasRoute,
  AppFinanceiroCentroDespesasRoute: AppFinanceiroCentroDespesasRoute,
  AppFinanceiroCentroRecebimentosRoute: AppFinanceiroCentroRecebimentosRoute,
  AppFinanceiroClientesFornecedoresRoute:
    AppFinanceiroClientesFornecedoresRoute,
  AppFinanceiroComissaoRoute: AppFinanceiroComissaoRoute,
  AppFinanceiroContasAPagarRoute: AppFinanceiroContasAPagarRoute,
  AppFinanceiroContasAReceberRoute: AppFinanceiroContasAReceberRoute,
  AppFinanceiroContratosRoute: AppFinanceiroContratosRoute,
  AppFinanceiroFluxoCaixaRoute: AppFinanceiroFluxoCaixaRoute,
  AppFinanceiroMovimentacaoRoute: AppFinanceiroMovimentacaoRoute,
  AppFinanceiroVisaoGeralRoute: AppFinanceiroVisaoGeralRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppClientesPerdidosRoute: typeof AppClientesPerdidosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConstrutorasRoute: typeof AppConstrutorasRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentacaoRoute: typeof AppDocumentacaoRoute
  AppEquipesRoute: typeof AppEquipesRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppFunilRoute: typeof AppFunilRoute
  AppFunilClientesRoute: typeof AppFunilClientesRoute
  AppGuiaRoute: typeof AppGuiaRoute
  AppImoveisRoute: typeof AppImoveisRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLeadsPerdidosRoute: typeof AppLeadsPerdidosRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppResultadoRoute: typeof AppResultadoRoute
  AppTaxaConversaoRoute: typeof AppTaxaConversaoRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppTriagemRoute: typeof AppTriagemRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVendasRoute: typeof AppVendasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppClientesPerdidosRoute: AppClientesPerdidosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConstrutorasRoute: AppConstrutorasRoute,
  AppContratosRoute: AppContratosRoute,
  AppCorretoresRoute: AppCorretoresRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentacaoRoute: AppDocumentacaoRoute,
  AppEquipesRoute: AppEquipesRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppFunilRoute: AppFunilRoute,
  AppFunilClientesRoute: AppFunilClientesRoute,
  AppGuiaRoute: AppGuiaRoute,
  AppImoveisRoute: AppImoveisRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLeadsPerdidosRoute: AppLeadsPerdidosRoute,
  AppMetasRoute: AppMetasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppResultadoRoute: AppResultadoRoute,
  AppTaxaConversaoRoute: AppTaxaConversaoRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppTriagemRoute: AppTriagemRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVendasRoute: AppVendasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemonstracaoRoute: DemonstracaoRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ProdutosCrmImobiliarioRoute: ProdutosCrmImobiliarioRoute,
  ProdutosIaWhatsappRoute: ProdutosIaWhatsappRoute,
  ProdutosSitesInstitucionaisRoute: ProdutosSitesInstitucionaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
