/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCorretoresRouteImport } from './routes/_app.corretores'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppFunilRouteImport } from './routes/_app.funil'
import { Route as AppImoveisRouteImport } from './routes/_app.imoveis'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPropostasRouteImport } from './routes/_app.propostas'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppTriagemRouteImport } from './routes/_app.triagem'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppFinanceiroCentroDespesasRouteImport } from './routes/_app.financeiro.centro-despesas'
import { Route as AppFinanceiroClientesFornecedoresRouteImport } from './routes/_app.financeiro.clientes-fornecedores'
import { Route as AppFinanceiroContasAPagarRouteImport } from './routes/_app.financeiro.contas-a-pagar'
import { Route as AppFinanceiroContasAReceberRouteImport } from './routes/_app.financeiro.contas-a-receber'
import { Route as AppFinanceiroDemonstrativoRouteImport } from './routes/_app.financeiro.demonstrativo'
import { Route as AppFinanceiroFluxoCaixaRouteImport } from './routes/_app.financeiro.fluxo-caixa'
import { Route as AppFinanceiroMovimentacaoRouteImport } from './routes/_app.financeiro.movimentacao'
import { Route as AppFinanceiroVisaoGeralRouteImport } from './routes/_app.financeiro.visao-geral'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFunilRoute = AppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisRoute = AppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppTriagemRoute = AppTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroCentroDespesasRoute =
  AppFinanceiroCentroDespesasRouteImport.update({
    id: '/centro-despesas',
    path: '/centro-despesas',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroClientesFornecedoresRoute =
  AppFinanceiroClientesFornecedoresRouteImport.update({
    id: '/clientes-fornecedores',
    path: '/clientes-fornecedores',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContasAPagarRoute =
  AppFinanceiroContasAPagarRouteImport.update({
    id: '/contas-a-pagar',
    path: '/contas-a-pagar',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContasAReceberRoute =
  AppFinanceiroContasAReceberRouteImport.update({
    id: '/contas-a-receber',
    path: '/contas-a-receber',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroDemonstrativoRoute =
  AppFinanceiroDemonstrativoRouteImport.update({
    id: '/demonstrativo',
    path: '/demonstrativo',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroFluxoCaixaRoute = AppFinanceiroFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroMovimentacaoRoute =
  AppFinanceiroMovimentacaoRouteImport.update({
    id: '/movimentacao',
    path: '/movimentacao',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroVisaoGeralRoute = AppFinanceiroVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppFinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/corretores': typeof AppCorretoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/funil': typeof AppFunilRoute
  '/imoveis': typeof AppImoveisRoute
  '/leads': typeof AppLeadsRoute
  '/metas': typeof AppMetasRoute
  '/perfil': typeof AppPerfilRoute
  '/propostas': typeof AppPropostasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/triagem': typeof AppTriagemRoute
  '/usuarios': typeof AppUsuariosRoute
  '/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/demonstrativo': typeof AppFinanceiroDemonstrativoRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/corretores': typeof AppCorretoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/funil': typeof AppFunilRoute
  '/imoveis': typeof AppImoveisRoute
  '/leads': typeof AppLeadsRoute
  '/metas': typeof AppMetasRoute
  '/perfil': typeof AppPerfilRoute
  '/propostas': typeof AppPropostasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/triagem': typeof AppTriagemRoute
  '/usuarios': typeof AppUsuariosRoute
  '/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/demonstrativo': typeof AppFinanceiroDemonstrativoRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/corretores': typeof AppCorretoresRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/_app/funil': typeof AppFunilRoute
  '/_app/imoveis': typeof AppImoveisRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/propostas': typeof AppPropostasRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/triagem': typeof AppTriagemRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/_app/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/_app/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/_app/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/_app/financeiro/demonstrativo': typeof AppFinanceiroDemonstrativoRoute
  '/_app/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/_app/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/_app/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/financeiro'
    | '/funil'
    | '/imoveis'
    | '/leads'
    | '/metas'
    | '/perfil'
    | '/propostas'
    | '/relatorios'
    | '/triagem'
    | '/usuarios'
    | '/financeiro/centro-despesas'
    | '/financeiro/clientes-fornecedores'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/demonstrativo'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/movimentacao'
    | '/financeiro/visao-geral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/financeiro'
    | '/funil'
    | '/imoveis'
    | '/leads'
    | '/metas'
    | '/perfil'
    | '/propostas'
    | '/relatorios'
    | '/triagem'
    | '/usuarios'
    | '/financeiro/centro-despesas'
    | '/financeiro/clientes-fornecedores'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/demonstrativo'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/movimentacao'
    | '/financeiro/visao-geral'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/corretores'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/funil'
    | '/_app/imoveis'
    | '/_app/leads'
    | '/_app/metas'
    | '/_app/perfil'
    | '/_app/propostas'
    | '/_app/relatorios'
    | '/_app/triagem'
    | '/_app/usuarios'
    | '/_app/financeiro/centro-despesas'
    | '/_app/financeiro/clientes-fornecedores'
    | '/_app/financeiro/contas-a-pagar'
    | '/_app/financeiro/contas-a-receber'
    | '/_app/financeiro/demonstrativo'
    | '/_app/financeiro/fluxo-caixa'
    | '/_app/financeiro/movimentacao'
    | '/_app/financeiro/visao-geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corretores': {
      id: '/_app/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funil': {
      id: '/_app/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AppFunilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imoveis': {
      id: '/_app/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AppImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propostas': {
      id: '/_app/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triagem': {
      id: '/_app/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AppTriagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/centro-despesas': {
      id: '/_app/financeiro/centro-despesas'
      path: '/centro-despesas'
      fullPath: '/financeiro/centro-despesas'
      preLoaderRoute: typeof AppFinanceiroCentroDespesasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/clientes-fornecedores': {
      id: '/_app/financeiro/clientes-fornecedores'
      path: '/clientes-fornecedores'
      fullPath: '/financeiro/clientes-fornecedores'
      preLoaderRoute: typeof AppFinanceiroClientesFornecedoresRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-a-pagar': {
      id: '/_app/financeiro/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof AppFinanceiroContasAPagarRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-a-receber': {
      id: '/_app/financeiro/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof AppFinanceiroContasAReceberRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/demonstrativo': {
      id: '/_app/financeiro/demonstrativo'
      path: '/demonstrativo'
      fullPath: '/financeiro/demonstrativo'
      preLoaderRoute: typeof AppFinanceiroDemonstrativoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/fluxo-caixa': {
      id: '/_app/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AppFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/movimentacao': {
      id: '/_app/financeiro/movimentacao'
      path: '/movimentacao'
      fullPath: '/financeiro/movimentacao'
      preLoaderRoute: typeof AppFinanceiroMovimentacaoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/visao-geral': {
      id: '/_app/financeiro/visao-geral'
      path: '/visao-geral'
      fullPath: '/financeiro/visao-geral'
      preLoaderRoute: typeof AppFinanceiroVisaoGeralRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
  }
}

interface AppFinanceiroRouteChildren {
  AppFinanceiroCentroDespesasRoute: typeof AppFinanceiroCentroDespesasRoute
  AppFinanceiroClientesFornecedoresRoute: typeof AppFinanceiroClientesFornecedoresRoute
  AppFinanceiroContasAPagarRoute: typeof AppFinanceiroContasAPagarRoute
  AppFinanceiroContasAReceberRoute: typeof AppFinanceiroContasAReceberRoute
  AppFinanceiroDemonstrativoRoute: typeof AppFinanceiroDemonstrativoRoute
  AppFinanceiroFluxoCaixaRoute: typeof AppFinanceiroFluxoCaixaRoute
  AppFinanceiroMovimentacaoRoute: typeof AppFinanceiroMovimentacaoRoute
  AppFinanceiroVisaoGeralRoute: typeof AppFinanceiroVisaoGeralRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCentroDespesasRoute: AppFinanceiroCentroDespesasRoute,
  AppFinanceiroClientesFornecedoresRoute:
    AppFinanceiroClientesFornecedoresRoute,
  AppFinanceiroContasAPagarRoute: AppFinanceiroContasAPagarRoute,
  AppFinanceiroContasAReceberRoute: AppFinanceiroContasAReceberRoute,
  AppFinanceiroDemonstrativoRoute: AppFinanceiroDemonstrativoRoute,
  AppFinanceiroFluxoCaixaRoute: AppFinanceiroFluxoCaixaRoute,
  AppFinanceiroMovimentacaoRoute: AppFinanceiroMovimentacaoRoute,
  AppFinanceiroVisaoGeralRoute: AppFinanceiroVisaoGeralRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppFunilRoute: typeof AppFunilRoute
  AppImoveisRoute: typeof AppImoveisRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTriagemRoute: typeof AppTriagemRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCorretoresRoute: AppCorretoresRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppFunilRoute: AppFunilRoute,
  AppImoveisRoute: AppImoveisRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMetasRoute: AppMetasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTriagemRoute: AppTriagemRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
